-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 17:05:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cscb532
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cscb532
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cscb532` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cscb532` ;

-- -----------------------------------------------------
-- Table `cscb532`.`logistic_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`logistic_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cscb532`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `company_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id` (`company_id` ASC) VISIBLE,
  CONSTRAINT `client_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `cscb532`.`logistic_company` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cscb532`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `role` ENUM('courier', 'office_staff') NOT NULL,
  `company_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id` (`company_id` ASC) VISIBLE,
  CONSTRAINT `employee_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `cscb532`.`logistic_company` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cscb532`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`office` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id` (`company_id` ASC) VISIBLE,
  CONSTRAINT `office_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `cscb532`.`logistic_company` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cscb532`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`shipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NULL DEFAULT NULL,
  `receiver_id` INT NULL DEFAULT NULL,
  `delivery_address` VARCHAR(255) NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL,
  `is_delivered` TINYINT(1) NULL DEFAULT '0',
  `office_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `price` DECIMAL(8,2) NULL DEFAULT NULL,
  `delivery_type` ENUM('office', 'address') NULL DEFAULT NULL,
  `employee_id` INT NULL DEFAULT NULL,
  `client_id` INT NULL DEFAULT NULL,
  `is_sent` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `sender_id` (`sender_id` ASC) VISIBLE,
  INDEX `receiver_id` (`receiver_id` ASC) VISIBLE,
  INDEX `office_id` (`office_id` ASC) VISIBLE,
  INDEX `fk_employee_shipment` (`employee_id` ASC) VISIBLE,
  INDEX `fk_client_shipment` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_shipment`
    FOREIGN KEY (`client_id`)
    REFERENCES `cscb532`.`client` (`id`),
  CONSTRAINT `fk_employee_shipment`
    FOREIGN KEY (`employee_id`)
    REFERENCES `cscb532`.`employee` (`id`),
  CONSTRAINT `shipment_ibfk_1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `cscb532`.`client` (`id`),
  CONSTRAINT `shipment_ibfk_2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `cscb532`.`client` (`id`),
  CONSTRAINT `shipment_ibfk_3`
    FOREIGN KEY (`office_id`)
    REFERENCES `cscb532`.`office` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cscb532`.`user_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cscb532`.`user_auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('employee', 'client') NOT NULL,
  `employee_id` INT NULL DEFAULT NULL,
  `client_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `fk_user_auth_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_user_auth_client` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_auth_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `cscb532`.`client` (`id`),
  CONSTRAINT `fk_user_auth_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `cscb532`.`employee` (`id`),
  CONSTRAINT `user_auth_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `cscb532`.`employee` (`id`),
  CONSTRAINT `user_auth_ibfk_2`
    FOREIGN KEY (`client_id`)
    REFERENCES `cscb532`.`client` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `cscb532` ;

-- -----------------------------------------------------
-- function calculate_shipment_price
-- -----------------------------------------------------

DELIMITER $$
USE `cscb532`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `calculate_shipment_price`(weight DECIMAL(5, 2), delivery_type ENUM('office', 'address')) RETURNS decimal(8,2)
    DETERMINISTIC
BEGIN
    DECLARE base_price DECIMAL(8, 2);
    
    -- Set base price based on delivery type
    IF delivery_type = 'office' THEN
        SET base_price = 5.00; -- Adjust this based on your pricing strategy
    ELSE
        SET base_price = 7.50; -- Adjust this based on your pricing strategy
    END IF;

    -- Calculate total price based on weight
    RETURN base_price + (weight * 1.50); -- Adjust the weight multiplier as needed
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
